### PR TITLE
Create MACE Team Folder and Wk1 WAR

### PR DESCRIPTION
**Pull request by faelsof**

### CODE REVIEW

**Comment by ahernmikej** [comment]
You have some extra spaces in your MD. Please correct and re-push.

**Comment by ahernmikej** [comment]
Please save this file as a .md so it will display properly.

**Comment by faelsof** [comment]
should be fixed, thank you.

**Comment by faelsof** [comment]
> Please save this file as a .md so it will display properly.

should be fixed, thank you.

**Pull request merged**
